import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar, SidebarSection } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MyClinic MD",
  description: "Generated by create next app",
};

const sidebarWidth = "250px";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section
          className="fixed left-0 top-0 h-full"
          style={{ width: sidebarWidth }}
        >
          <SidebarSection />
        </section>
        <section
          className="fixed top-0 right-0"
          style={{ width: `calc(100% - ${sidebarWidth})` }}
        >
          <Navbar />
        </section>
        {children}
      </body>
    </html>
  );
}
