#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ ! -f yarn.lock ]; then
  echo "Error: yarn.lock is missing. Please use Yarn as the package manager."
  exit 1
fi

if [ -f package-lock.json ]; then
  echo "Error: package-lock.json found. Use Yarn instead of npm."
  exit 1
fi
